dist: trusty
sudo: required
language: cpp
compiler: gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-7
            - g++-7
            - libpoppler-qt5-dev
            - pkg-config
before_install:
        - sudo add-apt-repository -y ppa:saiarcot895/myppa
        - sudo add-apt-repository -y ppa:beineri/opt-qt595-trusty
        - sudo apt-get update
        - sudo apt-get -y install apt-fast
        - sudo apt-fast install -y qt59-meta-minimal qt59base qt59tools qt59translations qt59websockets
        - pkg-config --cflags poppler-qt5
before_script:
        - QTDIR="/opt/qt59"
        - PATH="$QTDIR/bin:$PATH"
        - source /opt/qt59/bin/qt59-env.sh
script:
        # Link gcc-6 and g++-7 to their standard commands
        - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
        # Export CC and CXX to tell cmake which compiler to use
        - export CC=/usr/bin/gcc-7
        - export CXX=/usr/bin/g++-7
        # Check versions of gcc, g++ and cmake
        - gcc -v && g++ -v 
        - cd src
        - qmake
        - make
